import Route from '@ember/routing/route';

export default Route.extend({
  model() {
    return [
      { "state": "Alabama", "count": 2843 }, { "state": "Alaska", "count": 433 }, { "state": "Arizona", "count": 932 }, { "state": "Arkansas", "count": 294 }, { "state": "California", "count": 5394 }, { "state": "Colorado", "count": 1944 }, { "state": "Connecticut", "count": 980 }, { "state": "Delaware", "count": 28 }, { "state": "Florida", "count": 1740 }, { "state": "Georgia", "count": 837 }, { "state": "Hawaii", "count": 462 }, { "state": "Idaho", "count": 70 }, { "state": "Illinois",   "count": 362 }, { "state": "Indiana", "count": 739 }, { "state": "Iowa", "count": 253 }, { "state": "Kansas", "count": 329 }, { "state": "Kentucky", "count": 940 }, { "state": "Louisiana", "count": 263 }, { "state": "Maine", "count": 823 }, { "state": "Maryland", "count": 780 }, { "state": "Massachusetts", "count": 274 }, { "state": "Michigan", "count": 983 }, { "state": "Minnesota", "count": 274 }, { "state": "Mississippi", "count": 1308 }, { "state": "Missouri", "count": 284 }, { "state": "Montana", "count": 904 }, { "state": "Nebraska", "count": 274 }, { "state": "Nevada", "count": 190 }, { "state": "New Hampshire", "count": 278 }, { "state": "New Jersey", "count": 402 }, { "state": "New Mexico", "count": 943 }, { "state": "New York", "count": 2948 }, { "state": "North Carolina", "count": 383 }, { "state": "North Dakota", "count": 139 }, { "state": "Ohio", "count": 389 }, { "state": "Oklahoma", "count": 392 }, { "state": "Oregon", "count": 409 }, { "state": "Pennsylvania", "count": 893 }, { "state": "Rhode Island", "count": 194 }, { "state": "South Carolina", "count": 87 }, { "state": "South Dakota", "count": 158 }, { "state": "Tennessee", "count": 93 }, { "state": "Texas", "count": 3078 }, { "state": "Utah", "count": 563 }, { "state": "Vermont", "count": 183 }, { "state": "Virginia", "count": 394 }, { "state": "Washington", "count": 1303 }, { "state": "West Virginia", "count": 692 }, { "state": "Wisconsin", "count": 492 }, { "state": "Wyoming", "count": 673 }
    ];
  }
});
